import React from 'react'
import '@/styles/header.css'

const Header = () => {
  return (
    <>
      <header className="header">
        <nav className="navbar">
          <div className="nav-links">
            <a href="/">Home</a>
            <a href="/buider">Builds</a>
            <a href="#">Products</a>
            <a href="#">Complete Builds</a>
            <a href="#">Forum</a>
            <a href="#">Contact</a>
          </div>
          <div className="nav-buttons">
            <button className="btn">Sign in</button>
            <button className="btn">Register</button>
          </div>
        </nav>
      </header>

      <section className="hero">
        <h1>Pick Parts. Build Your PC.<br/ >Compare and Share.</h1>
        <p>We provide part selection, pricing, and compatibility guidance for do-it-yourself computer builders.</p>
        <button className="btn-primary">Start your build</button>
      </section>
      <section class="complete-builds">
          <div class="builds-text">
              <h2>Complete builds</h2>
              <p>Browse thousands of PC builds generated by users showing their partlist, photos, and overall build experience.</p>
              <button class="btn-primary">View Complete Builds</button>
          </div>
          <div class="builds-gallery">
              <div class="build-item">
                  <img src="pc_build.jpg" alt="PC Build"></img>
                  <div class="build-info">
                      <p class="user">User 1</p>
                      <p class="build-name">Example build</p>
                      <p class="build-specs">RTX 3070 Ti<br />16GB 3600 MHz</p>
                      <p class="price">$1234</p>
                  </div>
              </div>
              <div class="build-item">
                  <img src="pc_build.jpg" alt="PC Build"></img>
                  <div class="build-info">
                      <p class="user">User 1</p>
                      <p class="build-name">Example build</p>
                      <p class="build-specs">RTX 3070 Ti<br />16GB 3600 MHz</p>
                      <p class="price">$1234</p>
                  </div>
              </div>
              <div class="build-item">
                  <img src="pc_build.jpg" alt="PC Build"></img>
                  <div class="build-info">
                      <p class="user">User 1</p>
                      <p class="build-name">Example build</p>
                      <p class="build-specs">RTX 3070 Ti<br />16GB 3600 MHz</p>
                      <p class="price">$1234</p>
                  </div>
              </div>
          </div>
      </section>
      <section class="complete-builds">
          <div class="builds-text">
              <h2>Complete builds</h2>
              <p>Browse thousands of PC builds generated by users showing their partlist, photos, and overall build experience.</p>
              <button class="btn-primary">View Complete Builds</button>
          </div>
          <div class="builds-gallery">
              <div class="build-item">
                  <img src="pc_build.jpg" alt="PC Build"></img>
                  <div class="build-info">
                      <p class="user">User 1</p>
                      <p class="build-name">Example build</p>
                      <p class="build-specs">RTX 3070 Ti<br />16GB 3600 MHz</p>
                      <p class="price">$1234</p>
                  </div>
              </div>
              <div class="build-item">
                  <img src="pc_build.jpg" alt="PC Build"></img>
                  <div class="build-info">
                      <p class="user">User 1</p>
                      <p class="build-name">Example build</p>
                      <p class="build-specs">RTX 3070 Ti<br />16GB 3600 MHz</p>
                      <p class="price">$1234</p>
                  </div>
              </div>
              <div class="build-item">
                  <img src="pc_build.jpg" alt="PC Build"></img>
                  <div class="build-info">
                      <p class="user">User 1</p>
                      <p class="build-name">Example build</p>
                      <p class="build-specs">RTX 3070 Ti<br />16GB 3600 MHz</p>
                      <p class="price">$1234</p>
                  </div>
              </div>
          </div>
      </section>
    </>
  );
};

export default Header;
